### ISSUE TITLE
Issue using scenarios that are lists as question options - only the first list populates the question options

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#1130] opened 2024-10-09 23:59 UTC
See example where we have a `ScenarioList` that contains scenarios that are lists. When we use the lists as question options only the first list appears to be passed (the responses are all from the first list only):

https://www.expectedparrot.com/content/e355af8a-572b-4e70-af91-06edbd404639

**Comment by johnjosephhorton** [comment] 2024-10-14 12:50
The second one "worked" to render the prompt:

<img width="577" alt="Screenshot 2024-10-14 at 8 49 39 AM" src="https://github.com/user-attachments/assets/4545dd1f-9b36-4609-8bed-70264c8a71ea">

**Comment by johnjosephhorton** [comment] 2024-10-14 14:36
I can get this to work if an `Interview` instead makes a deepcopy of a pass-in survey:
 
```
from edsl import QuestionMultipleChoice, ScenarioList, Scenario

q = QuestionMultipleChoice(
    question_name="capital_of_france",
    question_text="What is the capital of France?",
    question_options="{{ question_options }}",
)

s = ScenarioList(
    [
        Scenario({"question_options": ["Paris", "London", "Berlin", "Madrid"]}),
        Scenario({"question_options": ["PARIS", "LONDON", "BERLIN", "MADRID"]}),
    ]
)

# results = q.by(s).show_prompts()

results = q.by(s).run()
```
This, however, breaks some other skip-logic: 
```
    def test_eos_skip_logic(self):
        from edsl.questions import QuestionMultipleChoice, QuestionYesNo
    
        q1 = QuestionMultipleChoice(
            question_name="snow_shoveling",
            question_text="Do you enjoy snow shoveling?",
            question_options=["Yes", "No", "I do not know"],
        )
    
        q2 = QuestionYesNo(
            question_name="own_shovel", question_text="Do you own a shovel?"
        )
    
        from edsl import Agent
    
        d = Agent()
    
        def answer_question_directly(self, question, scenario):
            return "No"
    
        d.add_direct_question_answering_method(answer_question_directly)
    
        survey = q1.add_question(q2).add_stop_rule(
            "snow_shoveling", "snow_shoveling == 'No'"
        )
        dag = survey.dag()
        # breakpoint()
    
        jobs = survey.by(d)
    
        from edsl.data.Cache import Cache
    
        results = jobs.run(cache=Cache())
        # with this skip logic, the second question should not be answered
>       assert results[0].answer["own_shovel"] == None
```
I suspect that the skip-logic depends on the pass-by-reference feature of a Survey in a way that is not obvious to me.

**Comment by johnjosephhorton** [comment] 2024-10-14 14:57
I suspect that Survey test was passing for the 'wrong' reason---when I switch the test to stop_on_exception = True, we get an exception unrelated to what I think we're changing. Not sure why old test passed:

```python
    def keys_between(self, start_q, end_q, right_inclusive=True):
        """Return a list of all question indices between start_q and end_q.
    
        Example usage:
    
        .. code-block:: python
    
            rule_collection = RuleCollection(num_questions=5)
            rule_collection.keys_between(1, 3)
            [2, 3]
            rule_collection.keys_between(1, 4)
            [2, 3, 4]
            rule_collection.keys_between(1, EndOfSurvey, right_inclusive=False)
            [2, 3]
    
        """
        # If it's the end of the survey, all questions between the start_q and the end of the survey
        # now depend on the start_q
        if end_q == EndOfSurvey:
            if self.num_questions is None:
                raise ValueError(
                    "Cannot determine DAG when EndOfSurvey and when num_questions is not known."
                )
            end_q = self.num_questions - 1
    
>       question_range = list(range(start_q + 1, end_q + int(right_inclusive)))
E       TypeError: 'EndOfSurveyParent' object cannot be interpreted as an integer
```

**Comment by johnjosephhorton** [comment] 2024-10-14 14:58
Plan: 
1. Fix this EoS exception issue
2. Go back to deepcopy of survey

**Comment by johnjosephhorton** [comment] 2024-10-14 16:50
I think the issue is that when I make a deepcopy of the survey, the "x == EndOfSurvey" code doesn't work because it's not a singleton anymore.

**Comment by johnjosephhorton** [comment] 2024-10-14 23:43
You be fixed in main @rbyh

**Closed** 2024-10-16 12:45 UTC
Labels: bug
